-- ==============================================================================
-- SCRIPT DE ACTUALIZACIÓN DEL CÓDIGO PENAL OFICIAL DE LOS ÁNGELES ROLEPLAY v1.1
-- Nombres limpios sin clase en el título, descripciones detalladas por artículo.
-- ==============================================================================

-- 1. Asegurar la columna 'clase'
ALTER TABLE codigopenal ADD COLUMN IF NOT EXISTS clase TEXT;

-- 2. Vaciar la tabla actual
TRUNCATE TABLE codigopenal;

-- 3. Inserción de artículos con nombres limpios y descripciones detalladas
INSERT INTO codigopenal (id, nombre, dinero, tiempo, categoria, descripcion, clase) VALUES
-- CAPÍTULO II. DELITOS CONTRA EL ORDEN PÚBLICO
  (2011, '§201 — Alteración del orden público', 1000, 6, 'Orden Público', 'Perturbación menor de la paz ciudadana y el orden público.', 'Misdemeanor'),
  (2012, '§201 — Alteración del orden público', 5000, 36, 'Orden Público', 'Perturbación grave del orden público con incitación o violencia.', 'Felony'),
  (202, '§202 — Conducta desordenada', 500, 0, 'Orden Público', 'Comportamiento inadecuado en vía pública.', 'Misdemeanor'),
  (203, '§203 — Escándalo público', 750, 6, 'Orden Público', 'Actos ofensivos o inmorales en lugares de acceso público.', 'Misdemeanor'),
  (2041, '§204 — Reunión ilegal', 1000, 6, 'Orden Público', 'Congregación no autorizada de personas que altera el orden.', 'Misdemeanor'),
  (2042, '§204 — Reunión ilegal', 0, 24, 'Orden Público', 'Congregación no autorizada efectuada con empleo de violencia.', 'Felony'),
  (205, '§205 — Disturbios civiles', 10000, 60, 'Orden Público', 'Alteración multitudinaria violenta contra personas o bienes.', 'Felony'),
  (206, '§206 — Incitación al caos', 7500, 48, 'Orden Público', 'Provocación deliberada de pánico o desorden generalizado.', 'Felony'),
  (2101, '§210 — Resistencia al arresto', 1000, 6, 'Orden Público', 'Oposición física pasiva o desobediencia a la detención.', 'Misdemeanor'),
  (2102, '§210 — Resistencia al arresto', 0, 36, 'Orden Público', 'Oposición violenta empleando fuerza o agresión contra los agentes.', 'Felony'),
  (211, '§211 — Evasión policial a pie', 1000, 6, 'Orden Público', 'Huir a pie de las autoridades para impedir el arresto.', 'Misdemeanor'),
  (212, '§212 — Evasión policial en vehículo', 0, 60, 'Orden Público', 'Huir a alta velocidad en vehículo poniendo en riesgo la vía pública.', 'Felony'),
  (213, '§213 — Negativa a identificarse', 500, 0, 'Orden Público', 'Rechazo a aportar documentación legítima requerida por oficiales.', 'Misdemeanor'),
  (214, '§214 — Obstrucción a un oficial', 1000, 0, 'Orden Público', 'Interferir o entorpecer las labores de un agente de servicio.', 'Misdemeanor'),
  (215, '§215 — Falsa declaración a la policía', 750, 6, 'Orden Público', 'Aportar datos mendaces o testimonios engañosos a la autoridad.', 'Misdemeanor'),
  (216, '§216 — Suplantación de funcionario público', 5000, 36, 'Orden Público', 'Hacerse pasar ilegítimamente por agente o empleado del gobierno.', 'Felony'),

-- CAPÍTULO III. DELITOS CONTRA LAS PERSONAS
  (301, '§301 — Agresión simple', 1000, 6, 'Personas', 'Ataque físico leve o amenaza inmediata sin armas.', 'Misdemeanor'),
  (302, '§302 — Agresión agravada', 10000, 48, 'Personas', 'Ataque físico severo con intención de causar daño corporal grave.', 'Felony'),
  (303, '§303 — Agresión con arma blanca', 1000, 60, 'Personas', 'Ataque o apuñalamiento mediante empleo de objeto punzocortante.', 'Felony'),
  (304, '§304 — Agresión con arma de fuego', 15000, 84, 'Personas', 'Disparar o atacar físicamente con armamento de fuego.', 'Felony'),
  (305, '§305 — Lesiones graves (Grievous bodily harm)', 12000, 72, 'Personas', 'Causar mutilación, desfiguración o lesiones permanentes.', 'Felony'),
  (310, '§310 — Secuestro', 25000, 120, 'Personas', 'Privación ilegal de libertad reteniendo a una persona contra su voluntad.', 'Felony'),
  (311, '§311 — Secuestro agravado', 50000, 240, 'Personas', 'Secuestro con extorsión, lesiones o peligro para la vida.', 'Felony'),
  (312, '§312 — Toma de rehenes', 75000, 300, 'Personas', 'Retener personas para exigir condiciones o chantajear autoridades.', 'Felony'),
  (313, '§313 — Detención ilegal', 10000, 60, 'Personas', 'Retención no autorizada de la libertad individual.', 'Felony'),
  (320, '§320 — Homicidio involuntario', 0, 96, 'Personas', 'Causar la muerte de una persona por imprudencia o negligencia.', 'Felony'),
  (321, '§321 — Homicidio voluntario', 0, 180, 'Personas', 'Causar la muerte intencionada durante una riña o arrebato.', 'Felony'),
  (322, '§322 — Asesinato en segundo grado', 0, 300, 'Personas', 'Homicidio intencional sin premeditación previa deliberada.', 'Felony'),
  (323, '§323 — Asesinato en primer grado', 0, 300, 'Personas', 'Homicidio premeditado con alevosía y planificación previa.', 'Felony'),
  (324, '§324 — Intento de homicidio', 0, 180, 'Personas', 'Ejecutar actos directos encaminados a matar a una persona.', 'Felony'),
  (325, '§325 — Asesinato de funcionario público', 0, 999, 'Personas', 'Asesinato cometido contra un agente del orden o autoridad.', 'Felony'),

-- CAPÍTULO IV. DELITOS CONTRA LA PROPIEDAD
  (401, '§401 — Hurto menor', 500, 3, 'Propiedad', 'Sustracción no violenta de bienes de escaso valor.', 'Misdemeanor'),
  (402, '§402 — Hurto mayor', 2500, 24, 'Propiedad', 'Sustracción de bienes u objetos de cuantioso valor.', 'Felony'),
  (403, '§403 — Robo con fuerza', 10000, 60, 'Propiedad', 'Sustracción rompiendo accesos o cerraduras.', 'Felony'),
  (404, '§404 — Robo a mano armada', 20000, 120, 'Propiedad', 'Atraco o sustracción amenazando con armas de fuego o blancas.', 'Felony'),
  (405, '§405 — Robo de vehículo', 0, 72, 'Propiedad', 'Sustracción ilegal o puenteo de automóvil privado.', 'Felony'),
  (406, '§406 — Robo de vehículo de emergencia', 15000, 96, 'Propiedad', 'Robo de ambulancias, patrullas de policía o camiones de bomberos.', 'Felony'),
  (407, '§407 — Robo bancario', 50000, 120, 'Propiedad', 'Atraco a entidad financiera o sucursal bancaria.', 'Felony'),
  (408, '§408 — Robo a comercio', 10000, 60, 'Propiedad', 'Atraco a local comercial, tienda o establecimiento.', 'Felony'),
  (409, '§409 — Robo a cajero automático', 20000, 96, 'Propiedad', 'Forzado, explosión o robo directo de terminal de cajero.', 'Felony'),
  (420, '§420 — Allanamiento de morada', 1000, 36, 'Propiedad', 'Entrada no autorizada en vivienda o domicilio particular.', 'Felony'),
  (421, '§421 — Allanamiento comercial', 1500, 48, 'Propiedad', 'Irrupción o entrada ilegítima en propiedad comercial privada.', 'Felony'),
  (422, '§422 — Entrada ilegal en zona restringida', 1000, 12, 'Propiedad', 'Acceder a recintos gubernamentales o militares no autorizados.', 'Misdemeanor'),
  (430, '§430 — Vandalismo menor', 500, 3, 'Propiedad', 'Pintadas, grafitis o daños leves a mobiliario.', 'Misdemeanor'),
  (431, '§431 — Vandalismo grave', 15000, 48, 'Propiedad', 'Destrucción intencionada de bienes privados o públicos.', 'Felony'),
  (432, '§432 — Daños a propiedad gubernamental', 15000, 72, 'Propiedad', 'Destrucción o sabotaje de bienes e instalaciones del Estado.', 'Felony'),
  (433, '§433 — Incendio provocado', 50000, 180, 'Propiedad', 'Prender fuego intencionadamente a inmuebles, vehículos o bosques.', 'Felony'),

-- CAPÍTULO V. DELITOS RELACIONADOS CON ARMAS
  (501, '§501 — Posesión ilegal de arma blanca', 1000, 6, 'Armas', 'Portar navajas prohibidas, machetes o armas blancas tácticas.', 'Misdemeanor'),
  (502, '§502 — Posesión ilegal de arma de fuego', 5000, 36, 'Armas', 'Tener en propiedad armas de fuego sin documentación legal.', 'Felony'),
  (503, '§503 — Porte de arma sin licencia', 2500, 36, 'Armas', 'Portar arma en la vía pública careciendo de licencia CCW.', 'Felony'),
  (504, '§504 — Posesión de arma restringida o prohibida', 10000, 60, 'Armas', 'Poseer armas automáticas, fusiles de asalto o explosivos.', 'Felony'),
  (505, '§505 — Tráfico de armas', 10000, 120, 'Armas', 'Comercialización o distribución ilícita de armamento.', 'Felony'),
  (510, '§510 — Exhibición amenazante de arma', 2500, 36, 'Armas', 'Empuñar o mostrar armas con fines de intimidación pública.', 'Felony'),
  (511, '§511 — Descarga negligente de arma de fuego', 5000, 36, 'Armas', 'Disparar accidentalmente por manipulación imprudente.', 'Felony'),
  (512, '§512 — Disparos en zona urbana', 10000, 60, 'Armas', 'Efectuar disparos en zonas pobladas poniendo en riesgo a transeúntes.', 'Felony'),
  (513, '§513 — Uso de arma en la comisión de un delito', 0, 120, 'Armas', 'Circunstancia agravante por emplear armas en otros ilícitos.', 'Agravante'),
  (514, '§514 — Posesión de arma con número de serie alterado', 15000, 48, 'Armas', 'Portar armamento con números borrados o limados.', 'Felony'),
  (515, '§515 — Transferencia ilegal de armas de fuego', 15000, 84, 'Armas', 'Vender o entregar pistolas o fusiles sin registro oficial.', 'Felony'),
  (516, '§516 — Posesión de arma por persona prohibida', 10000, 60, 'Armas', 'Porte de armas por ex-convictos o inhabilitados judiciales.', 'Felony'),
  (517, '§517 — Disparo desde vehículo en movimiento', 25000, 180, 'Armas', 'Efectuar tiroteos desde automóvil (Drive-by shooting).', 'Felony'),
  (518, '§518 — Uso de arma contra agente del orden', 0, 300, 'Armas', 'Abrir fuego o disparar deliberadamente contra miembros de la policía.', 'Felony'),
  (519, '§519 — Portación de arma en edificio gubernamental', 10000, 72, 'Armas', 'Introducir armamento en juzgados, comisarías o dependencias públicas.', 'Felony'),
  (520, '§520 — Fabricación ilegal de armas de fuego', 20000, 96, 'Armas', 'Ensamblar o modificar ilegalmente armas de fuego o impresas en 3D.', 'Felony'),

-- CAPÍTULO VI. DELITOS RELACIONADOS CON SUSTANCIAS CONTROLADAS
  (601, '§601 — Posesión de sustancias controladas', 5000, 36, 'Sustancias Controladas', 'Porte personal de drogas o estupefacientes no autorizados.', 'Misdemeanor'),
  (602, '§602 — Posesión con intención de distribución', 10000, 60, 'Sustancias Controladas', 'Porte de grandes cantidades dosificadas para menudeo.', 'Felony'),
  (603, '§603 — Posesión de material para producción', 7500, 48, 'Sustancias Controladas', 'Tener precursores químicos o básculas de precisión.', 'Felony'),
  (610, '§610 — Venta de sustancias controladas', 20000, 84, 'Sustancias Controladas', 'Comercializar estupefacientes en la vía pública o locales.', 'Felony'),
  (611, '§611 — Tráfico de sustancias controladas', 50000, 180, 'Sustancias Controladas', 'Transportar cargamentos masivos de sustancias ilícitas.', 'Felony'),
  (612, '§612 — Producción de sustancias controladas', 25000, 120, 'Sustancias Controladas', 'Sintetizar o procesar estupefacientes químicos.', 'Felony'),
  (613, '§613 — Operación de laboratorio ilegal', 30000, 120, 'Sustancias Controladas', 'Instalar o poner en marcha cocinas clandestinas de droga.', 'Felony'),
  (614, '§614 — Distribución a menores', 50000, 180, 'Sustancias Controladas', 'Vender o facilitar estupefacientes a personas menores de edad.', 'Felony'),
  (615, '§615 — Transporte para distribución', 20000, 96, 'Sustancias Controladas', 'Agravante por el traslado logístico de estupefacientes.', 'Agravante'),
  (616, '§616 — Asociación para el tráfico', 0, 144, 'Sustancias Controladas', 'Coordinar con redes delictivas la venta de narcóticos.', 'Felony'),
  (617, '§617 — Lavado de dinero del narcotráfico', 50000, 120, 'Sustancias Controladas', 'Bancarizar o blanquear beneficios de origen narco.', 'Felony'),
  (618, '§618 — Introducción en centro penitenciario', 15000, 84, 'Sustancias Controladas', 'Ingresar estupefacientes en comisarías o prisiones.', 'Felony'),
  (619, '§619 — Cultivo ilegal', 15000, 72, 'Sustancias Controladas', 'Plantaciones o invernaderos clandestinos no regulados.', 'Felony'),
  (620, '§620 — Conspiración relacionada con narcóticos', 25000, 120, 'Sustancias Controladas', 'Planificar operaciones de distribución narcótica.', 'Felony'),

-- CAPÍTULO VII. DELITOS ECONÓMICOS Y FRAUDE
  (701, '§701 — Fraude financiero', 25000, 72, 'Delitos Económicos', 'Engaño o estafa en operaciones bancarias o de inversión.', 'Felony'),
  (702, '§702 — Blanqueo de capitales', 50000, 120, 'Delitos Económicos', 'Introducir dinero ilícito en el circuito económico legal.', 'Felony'),
  (703, '§703 — Estafa comercial', 15000, 60, 'Delitos Económicos', 'Engaño cobrando bienes o servicios no prestados.', 'Felony'),
  (704, '§704 — Falsificación de documentos', 20000, 60, 'Delitos Económicos', 'Alterar escritura, contratos o pasaportes.', 'Felony'),
  (705, '§705 — Falsificación de identidad', 10000, 60, 'Delitos Económicos', 'Usar credenciales de otra persona para beneficio personal.', 'Felony'),
  (706, '§706 — Corrupción', 50000, 144, 'Delitos Económicos', 'Sobornos y mordidas en transacciones comerciales o institucionales.', 'Felony'),
  (707, '§707 — Soborno', 25000, 96, 'Delitos Económicos', 'Ofrecer dinero o dávidas a empleados o funcionarios.', 'Felony'),
  (708, '§708 — Fraude bancario', 50000, 120, 'Delitos Económicos', 'Manipular cuentas o saquear fondos mediante engaño.', 'Felony'),
  (709, '§709 — Fraude informático', 20000, 84, 'Delitos Económicos', 'Hackeo o accesos no autorizados a sistemas financieros.', 'Felony'),
  (710, '§710 — Apropiación indebida', 15000, 60, 'Delitos Económicos', 'Quedarse con bienes o fondos depositados en custodia.', 'Felony'),
  (711, '§711 — Evasión fiscal', 30000, 96, 'Delitos Económicos', 'Ocultar ingresos para impagar tributos obligatorios.', 'Felony'),
  (712, '§712 — Falsificación de moneda', 50000, 144, 'Delitos Económicos', 'Imprimir o distribuir billetes falsos.', 'Felony'),
  (713, '§713 — Uso fraudulento de tarjetas', 15000, 72, 'Delitos Económicos', 'Clonar o usar tarjetas de crédito sin autorización.', 'Felony'),
  (714, '§714 — Fraude en contratos públicos', 50000, 120, 'Delitos Económicos', 'Amañar licitaciones gubernamentales.', 'Felony'),
  (715, '§715 — Enriquecimiento ilícito de funcionario público', 50000, 120, 'Delitos Económicos', 'Incremento injustificado del patrimonio de autoridades.', 'Felony'),
  (716, '§716 — Ocultación de registros financieros', 20000, 72, 'Delitos Económicos', 'Destruir contabilidad para tapar delitos fiscales.', 'Felony'),
  (717, '§717 — Conspiración para fraude económico', 25000, 96, 'Delitos Económicos', 'Planificar estafas masivas o entramados financieros.', 'Felony'),

-- CAPÍTULO VIII. DELITOS CONTRA LA ADMINISTRACIÓN PÚBLICA
  (801, '§801 — Corrupción de funcionario público', 50000, 144, 'Administración Pública', 'Aceptar dinero para alterar resoluciones de gobierno.', 'Felony'),
  (802, '§802 — Abuso de autoridad', 10000, 72, 'Administración Pública', 'Ejercer atribuciones infringiendo derechos constitucionales.', 'Felony'),
  (803, '§803 — Divulgación no autorizada de información confidencial', 10000, 60, 'Administración Pública', 'Filtrar atestados o datos secretos del estado.', 'Felony'),
  (804, '§804 — Obstrucción a la justicia', 10000, 48, 'Administración Pública', 'Dificultar investigaciones policiales o diligencias.', 'Felony'),
  (805, '§805 — Desacato a la autoridad judicial', 1000, 6, 'Administración Pública', 'Desobedecer citaciones o mandatos directos de un juez.', 'Misdemeanor'),
  (806, '§806 — Perjurio', 10000, 48, 'Administración Pública', 'Mentir bajo juramento en juicios o vistas legales.', 'Felony'),
  (807, '§807 — Manipulación o destrucción de pruebas', 15000, 72, 'Administración Pública', 'Ocultar o alterar evidencias de un escenario delictivo.', 'Felony'),
  (808, '§808 — Presentación de denuncia falsa', 0, 36, 'Administración Pública', 'Imputar delitos falsos ante la policía o juzgado.', 'Felony'),
  (809, '§809 — Fuga de custodia legal', 0, 60, 'Administración Pública', 'Escapar estando bajo arresto en celda o traslado.', 'Felony'),
  (810, '§810 — Ayuda o facilitación de fuga', 15000, 72, 'Administración Pública', 'Colaborar o romper accesos para liberar a detenidos.', 'Felony'),
  (811, '§811 — Negativa a cumplir orden judicial', 0, 12, 'Administración Pública', 'Incumplir sentencias o mandamientos del tribunal.', 'Felony'),
  (812, '§812 — Usurpación de funciones públicas', 10000, 48, 'Administración Pública', 'Ejercer cargos estatales careciendo de nombramiento.', 'Felony'),
  (813, '§813 — Interferencia en investigación oficial', 10000, 60, 'Administración Pública', 'Interferir deliberadamente en pesquisas abiertas.', 'Felony'),
  (814, '§814 — Intimidación de testigos o víctimas', 25000, 96, 'Administración Pública', 'Amenazar o coaccionar a testigos de juicios.', 'Felony'),
  (815, '§815 — Represalias contra testigos o funcionarios', 30000, 120, 'Administración Pública', 'Atacar física o verbalmente a peritos o jueces.', 'Felony'),
  (816, '§816 — Conspiración para obstruir la justicia', 20000, 96, 'Administración Pública', 'Conchabarse para impedir actuaciones judiciales.', 'Felony'),

-- CAPÍTULO IX. DELITOS DE TRÁNSITO Y CONDUCCIÓN
  (901, '§901 — Exceso de velocidad menor', 250, 0, 'Tránsito', 'Exceder en menos de 20 mph el límite permitido.', 'Infraction'),
  (902, '§902 — Exceso de velocidad grave', 1000, 0, 'Tránsito', 'Exceder en más de 30 mph el límite permitido.', 'Misdemeanor'),
  (903, '§903 — Conducción temeraria', 1000, 3, 'Tránsito', 'Conducir con desprecio manifiesto por la seguridad vial.', 'Misdemeanor'),
  (904, '§904 — Ignorar dispositivo o señal de tráfico', 300, 0, 'Tránsito', 'Saltarse semáforos en rojo o señales de STOP.', 'Infraction'),
  (905, '§905 — Conducción imprudente causando lesiones', 10000, 36, 'Tránsito', 'Atropello o colisión causando heridos.', 'Misdemeanor'),
  (906, '§906 — Participación en carreras ilegales', 5000, 36, 'Tránsito', 'Disputar carreras de velocidad no autorizadas.', 'Felony'),
  (907, '§907 — Organización de carreras ilegales', 10000, 48, 'Tránsito', 'Promover o coordinar eventos de picadas ilícitas.', 'Felony'),
  (908, '§908 — Conducción bajo la influencia (DUI)', 1000, 48, 'Tránsito', 'Conducir ebrio o bajo sustancias estupefacientes.', 'Felony'),
  (909, '§909 — Negativa a pruebas de sobriedad', 500, 0, 'Tránsito', 'Rechazar el etilómetro o test de drogas.', 'Misdemeanor'),
  (910, '§910 — Evasión policial a pie', 1000, 6, 'Tránsito', 'Huir corriendo de un control de tráfico.', 'Misdemeanor'),
  (911, '§911 — Evasión policial en vehículo', 10000, 60, 'Tránsito', 'Persecución policial a alta velocidad.', 'Felony'),
  (912, '§912 — Evasión policial causando lesiones', 15000, 84, 'Tránsito', 'Persecución con resultado de atropellos o heridos.', 'Felony'),
  (913, '§913 — Atropello y fuga (Hit and Run)', 1000, 6, 'Tránsito', 'Abandonar la escena del accidente tras provocar daños.', 'Misdemeanor'),
  (914, '§914 — Atropello y fuga con lesiones', 10000, 48, 'Tránsito', 'Abandonar la escena habiendo personas heridos.', 'Felony'),
  (915, '§915 — Atropello y fuga con resultado de muerte', 20000, 120, 'Tránsito', 'Fugarse tras atropello mortal.', 'Felony'),
  (916, '§916 — Conducción sin licencia válida', 500, 1, 'Tránsito', 'Conducir careciendo de permiso de conducir.', 'Misdemeanor'),
  (917, '§917 — Conducción con licencia suspendida', 1000, 6, 'Tránsito', 'Circular con el carnet de conducir retirado.', 'Misdemeanor'),
  (918, '§918 — Vehículo no registrado', 250, 0, 'Tránsito', 'Circular con automóvil sin matriculación.', 'Infraction'),
  (919, '§919 — Falta de seguro obligatorio', 500, 0, 'Tránsito', 'Circular sin póliza de seguro de automóvil.', 'Infraction'),
  (920, '§920 — Obstrucción del tráfico o abandono', 500, 1, 'Tránsito', 'Estacionar o abandonar vehículos bloqueando la vía.', 'Misdemeanor'),

-- CAPÍTULO X. DELITOS CONTRA LOS SERVICIOS DE EMERGENCIA
  (1001, '§1001 — Agresión a personal de emergencias', 1000, 60, 'Servicios de Emergencia', 'Atacar a médicos, paramédicos o bomberos.', 'Felony'),
  (1002, '§1002 — Interferencia con servicios de emergencia', 0, 16, 'Servicios de Emergencia', 'Bloquear el paso a ambulancias o camiones de bomberos.', 'Misdemeanor'),
  (1003, '§1003 — Robo de vehículo de emergencia', 15000, 96, 'Servicios de Emergencia', 'Sustraer vehículos de rescate de servicio.', 'Felony'),
  (1004, '§1004 — Uso fraudulento del 911', 1000, 0, 'Servicios de Emergencia', 'Realizar bromas o falsas alarmas a la línea de emergencias.', 'Misdemeanor'),
  (1005, '§1005 — Suplantación de personal de emergencias', 10000, 48, 'Servicios de Emergencia', 'Usar uniformes o insignias de paramédicos/bomberos.', 'Felony'),
  (1006, '§1006 — Daños a equipos de emergencia', 15000, 72, 'Servicios de Emergencia', 'Destruir material de rescate o extinción.', 'Felony'),
  (1007, '§1007 — Obstrucción de rescates', 0, 16, 'Servicios de Emergencia', 'Dificultar evacuaciones o labores de socorro.', 'Misdemeanor'),
  (1008, '§1008 — Amenazas contra personal de emergencias', 10000, 60, 'Servicios de Emergencia', 'Intimidar a sanitarios durante intervenciones.', 'Felony'),
  (1009, '§1009 — Agresión agravada contra personal de emergencias', 20000, 120, 'Servicios de Emergencia', 'Ataque físico violento causando lesiones a paramédicos.', 'Misdemeanor'),
  (1010, '§1010 — Uso indebido de distintivos de emergencias', 1000, 6, 'Servicios de Emergencia', 'Utilizar luces estroboscópicas o sirenas sin permiso.', 'Misdemeanor'),

-- CAPÍTULO XI. DELITOS ORGANIZADOS Y TERRORISMO CRIMINAL
  (1101, '§1101 — Participación en organización criminal', 25000, 96, 'Terrorismo y Crimen Organizado', 'Integrar bandas armadas o mafias estructuradas.', 'Felony'),
  (1102, '§1102 — Asociación delictiva', 15000, 60, 'Terrorismo y Crimen Organizado', 'Reunirse sistemáticamente para cometer ilícitos.', 'Felony'),
  (1103, '§1103 — Tráfico organizado', 15000, 144, 'Terrorismo y Crimen Organizado', 'Redes de contrabando masivo a gran escala.', 'Felony'),
  (1104, '§1104 — Terrorismo criminal', 100000, 999, 'Terrorismo y Crimen Organizado', 'Cometer matanzas o atentados con fines de amedrentar.', 'Felony'),
  (1105, '§1105 — Posesión de material explosivo', 25000, 120, 'Terrorismo y Crimen Organizado', 'Porte de C4, granadas o dinamita.', 'Felony'),
  (1106, '§1106 — Fabricación ilegal de explosivos', 30000, 144, 'Terrorismo y Crimen Organizado', 'Cocinar o ensamblar bombas caseras.', 'Felony'),
  (1107, '§1107 — Transporte ilícito de explosivos', 25000, 120, 'Terrorismo y Crimen Organizado', 'Mover material detonante sin medidas de seguridad.', 'Felony'),
  (1108, '§1108 — Financiación de organización terrorista', 50000, 180, 'Terrorismo y Crimen Organizado', 'Nutrir de fondos monetarios a grupos armados.', 'Felony'),
  (1109, '§1109 — Reclutamiento para organización criminal', 20000, 96, 'Terrorismo y Crimen Organizado', 'Captar nuevos miembros para bandas ilícitas.', 'Felony'),
  (1110, '§1110 — Reclutamiento de menores para actividades delictivas', 25000, 120, 'Terrorismo y Crimen Organizado', 'Inducir a niños o jóvenes a cometer delitos.', 'Felony'),
  (1111, '§1111 — Dirección o liderazgo de organización criminal', 75000, 240, 'Terrorismo y Crimen Organizado', 'Ejercer como cabecilla o capo de banda armada.', 'Felony'),
  (1112, '§1112 — Conspiración para actos terroristas', 100000, 999, 'Terrorismo y Crimen Organizado', 'Planear voladuras o matanzas colectivas.', 'Felony'),
  (1113, '§1113 — Utilización de explosivos durante un delito', 0, 100, 'Terrorismo y Crimen Organizado', 'Detonar bombas para facilitar robos o atracos.', 'Agravante'),
  (1114, '§1114 — Ataque contra infraestructura crítica', 75000, 300, 'Terrorismo y Crimen Organizado', 'Atacar centrales eléctricas, puentes o red de agua.', 'Felony'),
  (1115, '§1115 — Pertenencia continuada a organización criminal', 50000, 180, 'Terrorismo y Crimen Organizado', 'Reincidir en grupos armados tras salir de prisión.', 'Felony'),

-- CAPÍTULO XII. DELITOS FEDERALES Y MAYORES
  (1201, '§1201 — Robo a la Reserva Federal', 100000, 300, 'Delitos Federales y Mayores', 'Atraco de máxima escala al banco de reserva.', 'Felony'),
  (1202, '§1202 — Tráfico internacional ilícito', 75000, 240, 'Delitos Federales y Mayores', 'Ingreso de cargamentos internacionales prohibidos.', 'Felony'),
  (1203, '§1203 — Corrupción gubernamental mayor', 50000, 180, 'Delitos Federales y Mayores', 'Sobornos que afectan a altos mandos del Estado.', 'Felony'),
  (1204, '§1204 — Crímenes contra el Estado', 0, 999, 'Delitos Federales y Mayores', 'Traición, espionaje o intento de derrocamiento.', 'Felony'),
  (1205, '§1205 — Secuestro interestatal', 50000, 240, 'Delitos Federales y Mayores', 'Secuestro trasladando a la víctima fuera del condado.', 'Felony'),
  (1206, '§1206 — Tráfico de personas', 100000, 300, 'Delitos Federales y Mayores', 'Comercialización e inmigración ilegal forzada de seres humanos.', 'Felony'),
  (1207, '§1207 — Delitos contra funcionarios federales', 25000, 180, 'Delitos Federales y Mayores', 'Ataque a agentes del FBI, Marshals o jueces federales.', 'Felony'),
  (1208, '§1208 — Fraude federal agravado', 50000, 144, 'Delitos Federales y Mayores', 'Estafas masivas al Tesoro o agencias del gobierno.', 'Felony'),
  (1209, '§1209 — Conspiración para delitos federales', 25000, 120, 'Delitos Federales y Mayores', 'Planear violaciones graves del derecho federal.', 'Felony'),
  (1210, '§1210 — Lavado internacional de capitales', 75000, 180, 'Delitos Federales y Mayores', 'Mover fondos procedentes de mafias entre países.', 'Felony')
ON CONFLICT (id) DO UPDATE SET
  nombre = EXCLUDED.nombre,
  dinero = EXCLUDED.dinero,
  tiempo = EXCLUDED.tiempo,
  categoria = EXCLUDED.categoria,
  descripcion = EXCLUDED.descripcion,
  clase = EXCLUDED.clase;
